/**
 * Mapeo centralizado de elementos del DOM
 */
export const el = {
  // Workspaces & Sidebar
  wsPersonalBtn: document.getElementById('wsPersonalBtn'),
  wsEnterpriseBtn: document.getElementById('wsEnterpriseBtn'),
  foldersSectionLabel: document.getElementById('foldersSectionLabel'),
  sidebarWorkspaceBadge: document.getElementById('sidebarWorkspaceBadge'),
  topbarWorkspaceTag: document.getElementById('topbarWorkspaceTag'),
  manageTeamBtn: document.getElementById('manageTeamBtn'),
  letterheadConfigBtn: document.getElementById('letterheadConfigBtn'),
  quickPrintBtn: document.getElementById('quickPrintBtn'),
  folderList: document.getElementById('folderList'),
  newFolderInput: document.getElementById('newFolderInput'),
  addFolderBtn: document.getElementById('addFolderBtn'),
  folderTitle: document.getElementById('folderTitle'),
  folderEyebrow: document.getElementById('folderEyebrow'),
  sidebar: document.getElementById('sidebar'),
  sidebarBackdrop: document.getElementById('sidebarBackdrop'),
  hamburgerBtn: document.getElementById('hamburgerBtn'),
  sidebarCloseBtn: document.getElementById('sidebarCloseBtn'),
  trashBtn: document.getElementById('trashBtn'),
  trashCount: document.getElementById('trashCount'),
  exportBtn: document.getElementById('exportBtn'),
  importBtn: document.getElementById('importBtn'),
  importFileInput: document.getElementById('importFileInput'),

  // Dedicated Plan Pane & Templates
  planPane: document.getElementById('planPane'),
  templatesBar: document.getElementById('templatesBar'),
  goToEditorBtn: document.getElementById('goToEditorBtn'),
  planOpenLetterheadBtn: document.getElementById('planOpenLetterheadBtn'),
  planSaveReportBtn: document.getElementById('planSaveReportBtn'),
  planManageTeamBtn: document.getElementById('planManageTeamBtn'),

  // Editor Pane & Header Controls
  editorPane: document.getElementById('editorPane'),
  editor: document.getElementById('editor'),
  tagsInput: document.getElementById('tagsInput'),
  saveBtn: document.getElementById('saveBtn'),
  clearBtn: document.getElementById('clearBtn'),
  dictateBtn: document.getElementById('dictateBtn'),
  playBtn: document.getElementById('playBtn'),
  stopBtn: document.getElementById('stopBtn'),
  previewVoiceBtn: document.getElementById('previewVoiceBtn'),
  voiceSelect: document.getElementById('voiceSelect'),
  statusLine: document.getElementById('statusLine'),
  waveform: document.getElementById('waveform'),
  currentFolioBadge: document.getElementById('currentFolioBadge'),
  formalPrintBtn: document.getElementById('formalPrintBtn'),
  metaDrawerToggleBtn: document.getElementById('metaDrawerToggleBtn'),
  metaDrawerToggleText: document.getElementById('metaDrawerToggleText'),
  metaDrawerBody: document.getElementById('metaDrawerBody'),

  // Institutional Metadata Fields
  docTypeSelect: document.getElementById('docTypeSelect'),
  docFolioInput: document.getElementById('docFolioInput'),
  genFolioBtn: document.getElementById('genFolioBtn'),
  taskAssigneeSelect: document.getElementById('taskAssigneeSelect'),
  taskDueDate: document.getElementById('taskDueDate'),
  taskPrioritySelect: document.getElementById('taskPrioritySelect'),
  taskStatusSelect: document.getElementById('taskStatusSelect'),
  docAttendeesInput: document.getElementById('docAttendeesInput'),

  // Notes Pane & Filters
  notesPane: document.getElementById('notesPane'),
  notesPaneTitle: document.getElementById('notesPaneTitle'),
  notesList: document.getElementById('notesList'),
  notesCount: document.getElementById('notesCount'),
  tagFilterRow: document.getElementById('tagFilterRow'),
  sortSelect: document.getElementById('sortSelect'),
  searchInput: document.getElementById('searchInput'),
  searchClearBtn: document.getElementById('searchClearBtn'),
  searchGlobalCheckbox: document.getElementById('searchGlobalCheckbox'),
  searchGlobalLabel: document.getElementById('searchGlobalLabel'),
  enterpriseFiltersRow: document.getElementById('enterpriseFiltersRow'),
  statusFilterPills: document.getElementById('statusFilterPills'),
  viewModeDetailedBtn: document.getElementById('viewModeDetailedBtn'),
  viewModeCompactBtn: document.getElementById('viewModeCompactBtn'),
  mobileNotesBadge: document.getElementById('mobileNotesBadge'),

  // Navigation Tabs & Mobile Bottom Bar
  tabEditorBtn: document.getElementById('tabEditorBtn'),
  tabPlanBtn: document.getElementById('tabPlanBtn'),
  tabNotesBtn: document.getElementById('tabNotesBtn'),
  tabNotesLabel: document.getElementById('tabNotesLabel'),
  mobileNewNoteBtn: document.getElementById('mobileNewNoteBtn'),

  // Editor Options Menu
  editorOptionsBtn: document.getElementById('editorOptionsBtn'),
  editorOptionsMenu: document.getElementById('editorOptionsMenu'),
  autoSaveCheckbox: document.getElementById('autoSaveCheckbox'),
  autoSaveStatusLabel: document.getElementById('autoSaveStatusLabel'),
  formalPrintOptionRow: document.getElementById('formalPrintOptionRow'),
  optionsMenuDivider: document.getElementById('optionsMenuDivider'),

  // Global Dialog Modals
  modalOverlay: document.getElementById('modalOverlay'),
  modalTitle: document.getElementById('modalTitle'),
  modalText: document.getElementById('modalText'),
  modalCancel: document.getElementById('modalCancel'),
  modalConfirm: document.getElementById('modalConfirm'),

  // Trash Modal
  trashOverlay: document.getElementById('trashOverlay'),
  trashList: document.getElementById('trashList'),
  trashCloseBtn: document.getElementById('trashCloseBtn'),
  emptyTrashBtn: document.getElementById('emptyTrashBtn'),

  // Theme & Settings
  themeToggleBtn: document.getElementById('themeToggleBtn'),
  themeIcon: document.getElementById('themeIcon'),
  themeText: document.getElementById('themeText'),

  // Quick Preview Modal
  quickPreviewOverlay: document.getElementById('quickPreviewOverlay'),
  quickPreviewCloseX: document.getElementById('quickPreviewCloseX'),
  quickPreviewCloseBtn: document.getElementById('quickPreviewCloseBtn'),
  quickPreviewTitle: document.getElementById('quickPreviewTitle'),
  quickPreviewMeta: document.getElementById('quickPreviewMeta'),
  quickPreviewBadges: document.getElementById('quickPreviewBadges'),
  quickPreviewContent: document.getElementById('quickPreviewContent'),
  quickPreviewTags: document.getElementById('quickPreviewTags'),
  quickPreviewCopyBtn: document.getElementById('quickPreviewCopyBtn'),
  quickPreviewEditBtn: document.getElementById('quickPreviewEditBtn'),
  quickPreviewSpeakBtn: document.getElementById('quickPreviewSpeakBtn'),

  // Formal Sheet Modal (Corporate Print)
  formalPrintOverlay: document.getElementById('formalPrintOverlay'),
  formalPrintCloseX: document.getElementById('formalPrintCloseX'),
  formalPrintCloseBtn: document.getElementById('formalPrintCloseBtn'),
  doPrintBtn: document.getElementById('doPrintBtn'),
  copyFormalTextBtn: document.getElementById('copyFormalTextBtn'),
  editLetterheadFromPreviewBtn: document.getElementById('editLetterheadFromPreviewBtn'),

  // Institutional Sheet Elements
  sheetOrgLogo: document.getElementById('sheetOrgLogo'),
  sheetOrgName: document.getElementById('sheetOrgName'),
  sheetOrgDept: document.getElementById('sheetOrgDept'),
  sheetOrgSub: document.getElementById('sheetOrgSub'),
  sheetFolio: document.getElementById('sheetFolio'),
  sheetDate: document.getElementById('sheetDate'),
  sheetDocType: document.getElementById('sheetDocType'),
  sheetDepartment: document.getElementById('sheetDepartment'),
  sheetAssignee: document.getElementById('sheetAssignee'),
  sheetDeadline: document.getElementById('sheetDeadline'),
  sheetPriority: document.getElementById('sheetPriority'),
  sheetStatus: document.getElementById('sheetStatus'),
  sheetAttendeesRow: document.getElementById('sheetAttendeesRow'),
  sheetAttendees: document.getElementById('sheetAttendees'),
  sheetDocTitle: document.getElementById('sheetDocTitle'),
  sheetDocBody: document.getElementById('sheetDocBody'),
  sheetSigAuthorName: document.getElementById('sheetSigAuthorName'),
  sheetSigAuthorTitle: document.getElementById('sheetSigAuthorTitle'),
  sheetSigReviewerName: document.getElementById('sheetSigReviewerName'),
  sheetSigReviewerTitle: document.getElementById('sheetSigReviewerTitle'),
  sheetFooterLegal: document.getElementById('sheetFooterLegal'),

  // Letterhead Config Modal
  letterheadOverlay: document.getElementById('letterheadOverlay'),
  letterheadCloseX: document.getElementById('letterheadCloseX'),
  letterheadCancelBtn: document.getElementById('letterheadCancelBtn'),
  letterheadForm: document.getElementById('letterheadForm'),
  cfgOrgName: document.getElementById('cfgOrgName'),
  cfgOrgDept: document.getElementById('cfgOrgDept'),
  cfgOrgSub: document.getElementById('cfgOrgSub'),
  cfgOrgLogo: document.getElementById('cfgOrgLogo'),
  cfgLogoFile: document.getElementById('cfgLogoFile'),
  cfgSigAuthor: document.getElementById('cfgSigAuthor'),
  cfgSigReviewer: document.getElementById('cfgSigReviewer'),
  cfgFooterLegal: document.getElementById('cfgFooterLegal'),

  // Team Modal
  teamOverlay: document.getElementById('teamOverlay'),
  teamCloseX: document.getElementById('teamCloseX'),
  teamCloseBtn: document.getElementById('teamCloseBtn'),
  addMemberForm: document.getElementById('addMemberForm'),
  memberFullName: document.getElementById('memberFullName'),
  memberRole: document.getElementById('memberRole'),
  memberDept: document.getElementById('memberDept'),
  teamMemberCount: document.getElementById('teamMemberCount'),
  teamList: document.getElementById('teamList'),

  // Template Confirm Modal
  templateConfirmOverlay: document.getElementById('templateConfirmOverlay'),
  templateCancelBtn: document.getElementById('templateCancelBtn'),
  templateAppendBtn: document.getElementById('templateAppendBtn'),
  templateReplaceBtn: document.getElementById('templateReplaceBtn'),

  // Settings Modal
  settingsBtn: document.getElementById('settingsBtn'),
  settingsOverlay: document.getElementById('settingsOverlay'),
  settingsCloseX: document.getElementById('settingsCloseX'),
  settingsCloseBtn: document.getElementById('settingsCloseBtn'),

  // Auth & Profile
  userAuthWidget: document.getElementById('userAuthWidget'),
  userLoginTriggerBtn: document.getElementById('userLoginTriggerBtn'),
  userAuthLabel: document.getElementById('userAuthLabel'),
  userProfileDropdown: document.getElementById('userProfileDropdown'),
  userAvatar: document.getElementById('userAvatar'),
  userDisplayName: document.getElementById('userDisplayName'),
  userEmail: document.getElementById('userEmail'),
  userAccountBadge: document.getElementById('userAccountBadge'),
  syncStatusItem: document.getElementById('syncStatusItem'),
  syncStatusText: document.getElementById('syncStatusText'),
  userLogoutBtn: document.getElementById('userLogoutBtn'),

  // Auth Modal
  authModalOverlay: document.getElementById('authModalOverlay'),
  authModalCloseX: document.getElementById('authModalCloseX'),
  authModalCloseBtn: document.getElementById('authModalCloseBtn'),
  googleAuthBtn: document.getElementById('googleAuthBtn'),
  emailAuthForm: document.getElementById('emailAuthForm'),
  authNameGroup: document.getElementById('authNameGroup'),
  authNameInput: document.getElementById('authNameInput'),
  authEmailInput: document.getElementById('authEmailInput'),
  authPasswordInput: document.getElementById('authPasswordInput'),
  authErrorMsg: document.getElementById('authErrorMsg'),
  emailAuthSubmitBtn: document.getElementById('emailAuthSubmitBtn'),
  authTogglePrompt: document.getElementById('authTogglePrompt'),
  authToggleModeBtn: document.getElementById('authToggleModeBtn')
};
